export const FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID';
export const FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET';

export const JWT_SECRET = 'JWT_SECRET';
export const JWT_TOKEN_MAX_AGE = 'JWT_TOKEN_MAX_AGE';
export const FRONTEND_URL = 'FRONTEND_URL';

export const POSTGRES_URL = 'POSTGRES_URL';
