export enum ERROR_CODES {
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',

  EMPTY_PASSWORD = 'EMPTY_PASSWORD',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  WRONG_PASSWORD = 'WRONG_PASSWORD',

  USER_EXISTS = 'USER_EXISTS',
  USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  MATCHES_NOT_FOUND = 'MATCHES_NOT_FOUND',
  MATCH_BY_ID_NOT_FOUND = 'MATCH_BY_ID_NOT_FOUND',
  QUEUE_FOR_PENDING_STAGE_ALREADY_CREATED = 'QUEUE_FOR_PENDING_STAGE_ALREADY_CREATED',
  MUST_HAVE_AT_LEAST_TWO_BOTS = 'MUST_HAVE_AT_LEAST_TWO_BOTS',

  GAME_NOT_FOUND = 'GAME_NOT_FOUND',

  EMPTY_FILE = 'EMPTY_FILE',

  IN_PROGRESS_OR_FINISHED_STAGE_NOT_FOUND = 'IN_PROGRESS_OR_FINISHED_STAGE_NOT_FOUND',
  FINISHED_STAGE_NOT_FOUND = 'FINISHED_STAGE_NOT_FOUND',
  PENDING_STAGE_NOT_FOUND = 'PENDING_STAGE_NOT_FOUND',
  GAME_NOT_STARTED = 'GAME_NOT_STARTED',

  BOTS_NOT_FOUND = 'BOTS_NOT_FOUND',

  BOT_STATISTICS_MATCH_RESULT_SHOULD_BE_CREATED = 'BOT_STATISTICS_MATCH_RESULT_SHOULD_BE_CREATED',
  BOT_STATISTICS_FOR_BOTH_BOTS_SHOULD_BE_CREATED = 'BOT_STATISTICS_FOR_BOTH_BOTS_SHOULD_BE_CREATED',
  BOT_STATISTICS_PAGE_NOT_FOUND = 'BOT_STATISTICS_PAGE_NOT_FOUND',
}
